#!/bin/bash



export ANT_HOME=/sw/lib/ant
C=`pwd`
for x in `ls lib/*jar`; do 
      export CLASSPATH=$C/$x:${CLASSPATH}
done
cd src
javac */*.java */*/*java
for x in `find . -iname "*class"`; do
    mv $x ../bin/$x
done

cd ..
ant

