#!/usr/bin/perl
# Converts files that are produced by the SNPRelat R package
# into the same format that eigenstrat produces



my $out;


$len=(@ARGV);

if ($len==0) {
    print "Usage: ".
          "      snprelat2evec  INPUT \n".
          "      snprelat2evec  INPUT OUTPUT\n".
          "  \n".
          "  INPUT is the file name of a file produced by SNRelat\n".
          "  If no output file is given, output is to standard output.\n".
          "  If OUTPUT is given a file with that name is created, deleting any existing file with that name.\n";
}
             

$finp = $ARGV[0];


if ($len == 1) {
    $out = *STDOUT;
}

if ($len == 2) {
    $fout=$ARGV[1];
    open($out,">$fout");
}


open(INP,$finp);
while ($line = <INP>) {
    if (substr($line,0,1) eq "#") {
	print $out $line;
	next;
    }

    if ($line =~ /\s*\w+\s+(\w+)(\s+|-)(\w+)\s+(.*)/) {

    } else {
	print "No match:$line\n";
    }
    print $out "$1:$3\t$4\n";
}

close($out);
